In [ ]:
COMPANIES = [
    {
        "company_id": "431",
        "symbol": "SAMP",
        "name": "SAMPATH BANK PLC",
        "sector": "Banking"
    },
    {
        "company_id": "386",
        "symbol": "NDB",
        "name": "NATIONAL DEVELOPMENT BANK PLC",
        "sector": "Banking"
    },
    {
        "company_id": "442",
        "symbol": "DOCK",
        "name": "COLOMBO DOCKYARD PLC",
        "sector": "Capital Goods"
    },
]

In [ ]:
import os
import re
import time
import requests
import pandas as pd

API_URL = "https://www.cse.lk/api/getFinancialAnnouncement"
CDN_BASE = "https://cdn.cse.lk/"



def safe_filename(text, max_len=180):
    text = re.sub(r"[^\w\s.-]", "", str(text))
    text = re.sub(r"\s+", "_", text.strip())
    return text[:max_len]

def classify_report_type(file_text):
    text = str(file_text).lower()

    if "annual report" in text or "audited financial" in text:
        return "annual"

    if "interim financial" in text or "quarter" in text or "period ended" in text:
        return "interim"

    return "other"

def fetch_financial_reports(company, start_date, end_date):
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Content-Type": "application/x-www-form-urlencoded"
    }

    payload = {
        "companyIds": company["company_id"],
        "fromDate": start_date,
        "toDate": end_date
    }

    response = requests.post(API_URL, headers=headers, data=payload, timeout=60)
    response.raise_for_status()

    records = response.json().get("reqFinancialAnnouncemnets", [])

    df = pd.DataFrame(records)

    if df.empty:
        return df

    df["company_id"] = company["company_id"]
    df["expected_symbol"] = company["symbol"]
    df["expected_company_name"] = company["name"]
    df["sector"] = company.get("sector", "")
    df["pdf_url"] = CDN_BASE + df["path"]
    df["report_type"] = df["fileText"].apply(classify_report_type)

    return df

def download_pdf(url, save_path):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    if os.path.exists(save_path):
        print("Already exists:", save_path)
        return "exists"

    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=90
    )
    response.raise_for_status()

    if "pdf" not in response.headers.get("content-type", "").lower():
        print("Not PDF:", url)
        return "not_pdf"

    with open(save_path, "wb") as f:
        f.write(response.content)

    print("Downloaded:", save_path)
    return "downloaded"

def download_company_reports(company, start_date, end_date, base_dir="cse_reports"):
    print(f"\nFetching: {company['symbol']} - {company['name']}")

    df = fetch_financial_reports(company, start_date, end_date)

    if df.empty:
        print("No records found")
        return df

    company_folder = safe_filename(f"{company['symbol']}_{company['name']}")

    statuses = []

    for _, row in df.iterrows():
        filename = safe_filename(
            f"{row['symbol']}_{row['uploadedDate']}_{row['fileText']}"
        ) + ".pdf"

        save_path = os.path.join(
            base_dir,
            company_folder,
            row["report_type"],
            filename
        )

        try:
            status = download_pdf(row["pdf_url"], save_path)
        except Exception as e:
            print("Failed:", row["pdf_url"], "|", e)
            status = "failed"

        statuses.append(status)
        time.sleep(0.5)

    df["download_status"] = statuses

    metadata_path = os.path.join(base_dir, company_folder, "metadata.csv")
    os.makedirs(os.path.dirname(metadata_path), exist_ok=True)
    df.to_csv(metadata_path, index=False)

    print("Metadata saved:", metadata_path)

    return df

def run_cse_report_download(companies, start_date, end_date, base_dir="cse_reports"):
    all_results = []

    for company in companies:
        try:
            company_df = download_company_reports(
                company=company,
                start_date=start_date,
                end_date=end_date,
                base_dir=base_dir
            )

            if not company_df.empty:
                all_results.append(company_df)

        except Exception as e:
            print(f"Company failed: {company['symbol']} | {e}")

        time.sleep(1)

    if all_results:
        final_df = pd.concat(all_results, ignore_index=True)
    else:
        final_df = pd.DataFrame()

    master_metadata_path = os.path.join(base_dir, "master_metadata.csv")
    os.makedirs(base_dir, exist_ok=True)
    final_df.to_csv(master_metadata_path, index=False)

    print("\nDone")
    print("Total records:", len(final_df))
    print("Master metadata:", master_metadata_path)

    return final_df

In [ ]:
result_df = run_cse_report_download(
    companies=COMPANIES,
    start_date="2021-01-01",
    end_date="2026-05-01",
    base_dir="cse_reports"
)

Fetching: SAMP - SAMPATH BANK PLC
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_04_Mar_2026_025317_PM_Annual_Report_as_at_31st_December_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_20_Feb_2026_082839_AM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_13_Nov_2025_081726_AM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_14_Aug_2025_082153_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_14_May_2025_050009_PM_Interim_Financial_Statements_for_the_period_ended_31st_March_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_01_Apr_2025_101343_AM_Trust_Deed_-_BASEL_III_Compliant_Debenture_Issue_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_01_Apr_2025_101246_AM_Prospectus_-_BASEL_III_Compliant_Debenture_Issue_2025.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_04_Mar_2025_023320_PM_Sampath_Bank_PLC_-_Annual_Report_2024.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_18_Feb_2025_083650_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2024.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_13_Nov_2024_044943_PM_Interim_Financial_Statements_for_the_period_ended_30th_September_2024.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_08_Aug_2024_082942_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2024.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_14_May_2024_084610_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2024.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_29_Feb_2024_044338_PM_Sampath_Bank_PLC_-_Annual_Report_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_15_Feb_2024_090043_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_14_Nov_2023_083219_AM_Interim_Financial_Statements_for_the_period_ended_30th_September_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_14_Aug_2023_083414_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_15_May_2023_023450_PM_Interim_Financial_Statements_for_the_period_ended_31st_March_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_03_Mar_2023_032148_PM_Sampath_Bank_PLC_-_Annual_Report_2022.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_17_Feb_2023_095731_PM_Interim_Financial_Statements_for_the_year_ended_31st_December_2022.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_15_Feb_2023_120538_PM_Supplementary_Trust_Deed_-_Basel_III_Debenture_Issue_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_15_Feb_2023_120245_PM_Trust_Deed_-_Basel_III_Debenture_Issue_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_15_Feb_2023_120136_PM_Prospectus_-_Basel_III_Debenture_Issue_2023.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_11_Nov_2022_085915_AM_Interim_Financial_Statements_as_of_30092022.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_12_Aug_2022_085626_AM_Audited_Interim_Financial_Statements_for_the_period_ended_30th_June_2022.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_13_May_2022_083359_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2022.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_04_Mar_2022_040922_PM_Sampath_Bank_PLC_-_Annual_Report_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_17_Feb_2022_083049_AM_Sampath_Bank_PLC_-_Interim_Financial_Statements_for_the_year_ended_31st_December_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_12_Nov_2021_091415_AM_Interim_Financial_Statements_for_the_period_ended_30th_September_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_13_Aug_2021_084023_AM_Sampath_Bank_PLC_-_Interim_Financial_Statements_for_the_period_ended_30th_June_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_12_May_2021_120000_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_22_Apr_2021_091601_AM_Trust_Deed_-_BASEL_III_Debenture_Issue_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/other/SAMP_22_Apr_2021_091507_AM_Prospectus_-_BASEL_III_Debenture_Issue_2021.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/annual/SAMP_05_Mar_2021_023337_PM_Sampath_Bank_PLC_-_Annual_Report_2020.pdf
Already exists: cse_reports/SAMP_SAMPATH_BANK_PLC/interim/SAMP_16_Feb_2021_114029_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2020.pdf
Metadata saved: cse_reports/SAMP_SAMPATH_BANK_PLC/metadata.csv

Fetching: NDB - NATIONAL DEVELOPMENT BANK PLC
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_30_Apr_2026_041330_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_March_2026.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_24_Mar_2026_112119_AM_Prospectus.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_24_Mar_2026_112235_AM_Trust_Deed.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_24_Mar_2026_112347_AM_GSS_Bond_Framework.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_24_Mar_2026_112503_AM_Accountants_Report_and_Five_Year_Summary.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_04_Mar_2026_023916_PM_Annual_Report_as_at_31st_December_2025.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_25_Feb_2026_034455_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_04_Nov_2025_023242_PM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_Aug_2025_041749_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2025.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_May_2025_041238_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2025.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_05_Mar_2025_023231_PM_Annual_Report_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_20_Feb_2025_041558_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_06_Dec_2024_120131_PM_Trust_Deed_-_Basel_III_Compliant_Listed_Rated_Unsecured_Subordinated_Redeemable_Debenture_Issue_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_06_Dec_2024_120034_PM_Prospectus_-_Basel_III_Compliant_Listed_Rated_Unsecured_Subordinated_Redeemable_Debenture_Issue_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_13_Nov_2024_031840_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_23_Sep_2024_120000_AM_Trust_Deed_-_Basel_III_Compliant_Convertible_Debenture_Issue_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_23_Sep_2024_120000_AM_Prospectus_-_Basel_III_Compliant_Convertible_Debenture_Issue_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_Aug_2024_034851_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_May_2024_031303_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2024.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_05_Mar_2024_084042_AM_Annual_Report_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_20_Feb_2024_052044_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_22_Dec_2023_070141_PM_Trust_Deed_-_Basel_III_Compliant_Convertible_Debenture_Issue_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_22_Dec_2023_065929_PM_Prospectus_-_Basel_III_Compliant_Convertible_Debenture_Issue_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_Nov_2023_034149_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_Aug_2023_035458_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_12_May_2023_044826_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2023.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_07_Mar_2023_083141_AM_Annual_Report_2022_-_National_Development_Bank_PLC.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_21_Feb_2023_034912_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2022.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_14_Nov_2022_043208_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2022.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_15_Aug_2022_035221_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2022.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_13_May_2022_035828_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2022.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_07_Mar_2022_084034_AM_Annual_Report_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_22_Feb_2022_033419_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_30_Nov_2021_105031_AM_Trust_Deed_-_Basel_III_Debenture_Issue_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/other/NDB_30_Nov_2021_104907_AM_Prospectus_-_Basel_III_Debenture_Issue_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_12_Nov_2021_033415_PM_Interim_Financial_Statements_30th_September_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_28_Jul_2021_025633_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_13_May_2021_033428_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2021.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/annual/NDB_15_Mar_2021_085204_AM_National_Development_Bank_PLC_-_Annual_Report_2020.pdf
Already exists: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/interim/NDB_18_Feb_2021_031522_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2020.pdf
Metadata saved: cse_reports/NDB_NATIONAL_DEVELOPMENT_BANK_PLC/metadata.csv

Fetching: DOCK - COLOMBO DOCKYARD PLC
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_30_Apr_2026_100702_PM_Audited_Financial_Statements_for_the_Period_ended_31st_March_2026.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_30_Apr_2026_053335_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_March_2026.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_05_Mar_2026_023907_PM_Errata_to_the_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_03_Mar_2026_042026_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_14_Nov_2025_032303_PM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_15_Aug_2025_033027_PM_Interim_Financial_Report_as_at_30-06-2025.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annual_Report_2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_19_May_2025_080220_AM_Interim_Financial_Report_as_at_31-03-2025.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_06_Mar_2025_044317_PM_Interim_Financial_Report_as_at_31-12-2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_19_Nov_2024_032519_PM_Interim_Financial_Report_as_at_30-09-2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_20_Aug_2024_043150_PM_Interim_Financial_Report_as_at_30-06-2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_21_May_2024_032137_PM_Interim_Financial_Report_as_at_31-03-2024.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_06_Mar_2024_043318_PM_Interim_Financial_Report_as_at_31-12-2023.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_21_Nov_2023_082649_AM_Interim_Financial_Report_as_at_30.09.2023.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_15_Aug_2023_025835_PM_Interim_Financial_Report_as_at_30-06-2023.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_15_May_2023_025852_PM_Interim_Financial_Report_as_at_31-03-2023.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_04_Apr_2023_090130_AM_Annual_Report_2022.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_07_Mar_2023_092001_AM_Interim_Financial_Report_as_at_31-12-2022.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_18_Nov_2022_062423_PM_Interim_Financial_Report_as_at_30-09-2022.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_18_Aug_2022_025722_PM_Interim_Financial_Report_as_at_30-06-2022.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_06_Jun_2022_062920_PM_Annual_Report_2021.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_23_May_2022_084856_AM_Interim_Financial_Report_as_at_31-03-2022.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_07_Mar_2022_041704_PM_Interim_Financial_Report_as_at_31-12-2021.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_15_Nov_2021_040919_PM_Interim_Financial_Report_as_at_30-09-2021.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_17_Aug_2021_094938_AM_Interim_Financial_Statements_as_of_30-06-2021.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_20_May_2021_050205_PM_Interim_Financial_Report_as_at_31-03-2021.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf
Already exists: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/interim/DOCK_04_Mar_2021_081433_PM_Interim_Financial_Report_as_at_31-12-2020.pdf
Metadata saved: cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/metadata.csv

Done
Total records: 104
Master metadata: cse_reports/master_metadata.csv

## Data Extraction

In [ ]:
!pip install PyMuPDF
import fitz

def extract_text(pdf_path):
    text = ""
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text += page.get_text()
    return text

Collecting PyMuPDF
  Downloading pymupdf-1.27.2.3-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (24 kB)
Downloading pymupdf-1.27.2.3-cp310-abi3-manylinux_2_28_x86_64.whl (25.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.0/25.0 MB 21.9 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.27.2.3

In [ ]:
# ead PDFs from cse_reports/
# Extract text using fitz
# Create one CSV with metadata + extracted text
# Save individual .txt files also

In [ ]:
import os
import re
import pandas as pd

INPUT_CSV = "cse_extracted/extracted_pdf_text.csv"
OUTPUT_DIR = "cse_structured"
COMPANY_OUTPUT_DIR = os.path.join(OUTPUT_DIR, "company_wise")
MASTER_OUTPUT_CSV = os.path.join(OUTPUT_DIR, "financial_metrics_master.csv")

os.makedirs(COMPANY_OUTPUT_DIR, exist_ok=True)

# -----------------------------
# Utility functions
# -----------------------------

def safe_filename(text, max_len=150):
    text = re.sub(r"[^\w\s.-]", "", str(text))
    text = re.sub(r"\s+", "_", text.strip())
    return text[:max_len]

def clean_number(value):
    if value is None:
        return None

    value = str(value).strip()

    # Handle brackets as negative values: (1,234) -> -1234
    negative = value.startswith("(") and value.endswith(")")

    value = value.replace("(", "").replace(")", "")
    value = value.replace(",", "")
    value = value.replace("Rs.", "")
    value = value.replace("Rs", "")
    value = value.strip()

    try:
        number = float(value)
        return -number if negative else number
    except:
        return None

def normalize_text(text):
    text = str(text)
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.lower()

def extract_first_number_after_term(text, term_patterns, window=250):
    normalized = normalize_text(text)

    for term_pattern in term_patterns:
        match = re.search(term_pattern, normalized, re.IGNORECASE)

        if not match:
            continue

        start = match.end()
        snippet = normalized[start:start + window]

        number_match = re.search(r"\(?-?\d[\d,]*(?:\.\d+)?\)?", snippet)

        if number_match:
            return clean_number(number_match.group(0))

    return None

def extract_period_from_text(text):
    normalized = normalize_text(text)

    patterns = [
        r"quarter ended\s+([0-9]{1,2}(?:st|nd|rd|th)?\s+[a-z]+\s+[0-9]{4})",
        r"period ended\s+([0-9]{1,2}(?:st|nd|rd|th)?\s+[a-z]+\s+[0-9]{4})",
        r"year ended\s+([0-9]{1,2}(?:st|nd|rd|th)?\s+[a-z]+\s+[0-9]{4})",
        r"as at\s+([0-9]{1,2}(?:st|nd|rd|th)?\s+[a-z]+\s+[0-9]{4})",
        r"as of\s+([0-9]{1,2}/[0-9]{1,2}/[0-9]{4})"
    ]

    for pattern in patterns:
        match = re.search(pattern, normalized)
        if match:
            return match.group(1)

    return None

def extract_year_from_text_or_filename(text, filename):
    combined = f"{text[:3000]} {filename}"
    match = re.search(r"(20[0-9]{2})", combined)
    return match.group(1) if match else None

def infer_quarter(text):
    normalized = normalize_text(text)

    if "31st march" in normalized or "31 march" in normalized or "31/03" in normalized:
        return "Q1"
    if "30th june" in normalized or "30 june" in normalized or "30/06" in normalized:
        return "Q2"
    if "30th september" in normalized or "30 september" in normalized or "30/09" in normalized:
        return "Q3"
    if "31st december" in normalized or "31 december" in normalized or "31/12" in normalized:
        return "Q4/FY"

    return None

# -----------------------------
# Metric patterns
# -----------------------------

METRIC_TERMS = {
    "revenue": [
        r"\brevenue\b",
        r"\btotal revenue\b",
        r"\bgross revenue\b"
    ],
    "interest_income": [
        r"\binterest income\b"
    ],
    "net_interest_income": [
        r"\bnet interest income\b"
    ],
    "total_operating_income": [
        r"\btotal operating income\b",
        r"\boperating income\b"
    ],
    "profit_before_tax": [
        r"\bprofit before tax\b",
        r"\bprofit /\(loss\) before tax\b",
        r"\bprofit \(loss\) before tax\b",
        r"\bprofit before income tax\b"
    ],
    "profit_after_tax": [
        r"\bprofit after tax\b",
        r"\bnet profit after tax\b",
        r"\bnet profit /\(loss\) after tax\b",
        r"\bprofit for the period\b",
        r"\bprofit for the year\b"
    ],
    "earnings_per_share": [
        r"\bearnings per share\b",
        r"\bbasic earnings per share\b",
        r"\beps\b"
    ],
    "total_assets": [
        r"\btotal assets\b"
    ],
    "total_liabilities": [
        r"\btotal liabilities\b"
    ],
    "equity": [
        r"\btotal equity\b",
        r"\bshareholders.? equity\b",
        r"\bshare holders.? fund\b"
    ],
    "dividend_per_share": [
        r"\bdividend per share\b"
    ]
}

# -----------------------------
# Main extraction function
# -----------------------------

def extract_metrics_from_row(row):
    text = row.get("extracted_text", "")
    filename = row.get("pdf_filename", "")

    result = {
        "company_folder": row.get("company_folder", ""),
        "report_type": row.get("report_type", ""),
        "pdf_filename": filename,
        "pdf_path": row.get("pdf_path", ""),
        "txt_path": row.get("txt_path", ""),
        "page_count": row.get("page_count", ""),
        "text_length": row.get("text_length", ""),
        "period": extract_period_from_text(text),
        "year": extract_year_from_text_or_filename(text, filename),
        "quarter": infer_quarter(text),
    }

    for metric_name, patterns in METRIC_TERMS.items():
        result[metric_name] = extract_first_number_after_term(text, patterns)

    return result

def run_company_wise_extraction(input_csv=INPUT_CSV):
    extracted_df = pd.read_csv(input_csv)

    print("Input records:", len(extracted_df))

    success_df = extracted_df[
        extracted_df["extraction_status"].astype(str).str.lower().eq("success")
    ].copy()

    print("Successful extracted PDFs:", len(success_df))

    records = []

    for i, (_, row) in enumerate(success_df.iterrows(), start=1):
        print(f"[{i}/{len(success_df)}] Extracting metrics:", row["pdf_filename"])
        records.append(extract_metrics_from_row(row))

    metrics_df = pd.DataFrame(records)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Save master file
    metrics_df.to_csv(MASTER_OUTPUT_CSV, index=False, encoding="utf-8-sig")
    print("Master metrics saved:", MASTER_OUTPUT_CSV)

    # Save company-wise files
    for company, group in metrics_df.groupby("company_folder"):
        company_file = safe_filename(company) + "_financial_metrics.csv"
        company_path = os.path.join(COMPANY_OUTPUT_DIR, company_file)

        group.to_csv(company_path, index=False, encoding="utf-8-sig")
        print("Company metrics saved:", company_path)

    return metrics_df

metrics_df = run_company_wise_extraction()

Input records: 104
Successful extracted PDFs: 104
[1/104] Extracting metrics: DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf
[2/104] Extracting metrics: DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf
[3/104] Extracting metrics: DOCK_30_Apr_2026_100702_PM_Audited_Financial_Statements_for_the_Period_ended_31st_March_2026.pdf
[4/104] Extracting metrics: DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annual_Report_2024.pdf
[5/104] Extracting metrics: DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf
[6/104] Extracting metrics: DOCK_04_Apr_2023_090130_AM_Annual_Report_2022.pdf
[7/104] Extracting metrics: DOCK_06_Jun_2022_062920_PM_Annual_Report_2021.pdf
[8/104] Extracting metrics: DOCK_07_Mar_2022_041704_PM_Interim_Financial_Report_as_at_31-12-2021.pdf
[9/104] Extracting metrics: DOCK_05_Mar_2026_023907_PM_Errata_to_the_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
[10/104] Extracting metrics: DOCK_23_May_2022_084856_AM_Interim_Financial_Report_as_at_31-03-2022.pdf
[11/104] Extracting metrics: DOCK_15_Aug_2023_025835_PM_Interim_Financial_Report_as_at_30-06-2023.pdf
[12/104] Extracting metrics: DOCK_15_May_2023_025852_PM_Interim_Financial_Report_as_at_31-03-2023.pdf
[13/104] Extracting metrics: DOCK_14_Nov_2025_032303_PM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
[14/104] Extracting metrics: DOCK_15_Nov_2021_040919_PM_Interim_Financial_Report_as_at_30-09-2021.pdf
[15/104] Extracting metrics: DOCK_30_Apr_2026_053335_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_March_2026.pdf
[16/104] Extracting metrics: DOCK_06_Mar_2025_044317_PM_Interim_Financial_Report_as_at_31-12-2024.pdf
[17/104] Extracting metrics: DOCK_21_Nov_2023_082649_AM_Interim_Financial_Report_as_at_30.09.2023.pdf
[18/104] Extracting metrics: DOCK_18_Aug_2022_025722_PM_Interim_Financial_Report_as_at_30-06-2022.pdf
[19/104] Extracting metrics: DOCK_18_Nov_2022_062423_PM_Interim_Financial_Report_as_at_30-09-2022.pdf
[20/104] Extracting metrics: DOCK_03_Mar_2026_042026_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
[21/104] Extracting metrics: DOCK_17_Aug_2021_094938_AM_Interim_Financial_Statements_as_of_30-06-2021.pdf
[22/104] Extracting metrics: DOCK_07_Mar_2023_092001_AM_Interim_Financial_Report_as_at_31-12-2022.pdf
[23/104] Extracting metrics: DOCK_21_May_2024_032137_PM_Interim_Financial_Report_as_at_31-03-2024.pdf
[24/104] Extracting metrics: DOCK_04_Mar_2021_081433_PM_Interim_Financial_Report_as_at_31-12-2020.pdf
[25/104] Extracting metrics: DOCK_19_Nov_2024_032519_PM_Interim_Financial_Report_as_at_30-09-2024.pdf
[26/104] Extracting metrics: DOCK_19_May_2025_080220_AM_Interim_Financial_Report_as_at_31-03-2025.pdf
[27/104] Extracting metrics: DOCK_20_Aug_2024_043150_PM_Interim_Financial_Report_as_at_30-06-2024.pdf
[28/104] Extracting metrics: DOCK_06_Mar_2024_043318_PM_Interim_Financial_Report_as_at_31-12-2023.pdf
[29/104] Extracting metrics: DOCK_20_May_2021_050205_PM_Interim_Financial_Report_as_at_31-03-2021.pdf
[30/104] Extracting metrics: DOCK_15_Aug_2025_033027_PM_Interim_Financial_Report_as_at_30-06-2025.pdf
[31/104] Extracting metrics: NDB_23_Sep_2024_120000_AM_Prospectus_-_Basel_III_Compliant_Convertible_Debenture_Issue_2024.pdf
[32/104] Extracting metrics: NDB_30_Nov_2021_105031_AM_Trust_Deed_-_Basel_III_Debenture_Issue_2021.pdf
[33/104] Extracting metrics: NDB_22_Dec_2023_065929_PM_Prospectus_-_Basel_III_Compliant_Convertible_Debenture_Issue_2023.pdf
[34/104] Extracting metrics: NDB_24_Mar_2026_112503_AM_Accountants_Report_and_Five_Year_Summary.pdf
[35/104] Extracting metrics: NDB_24_Mar_2026_112235_AM_Trust_Deed.pdf
[36/104] Extracting metrics: NDB_22_Dec_2023_070141_PM_Trust_Deed_-_Basel_III_Compliant_Convertible_Debenture_Issue_2023.pdf
[37/104] Extracting metrics: NDB_30_Nov_2021_104907_AM_Prospectus_-_Basel_III_Debenture_Issue_2021.pdf
[38/104] Extracting metrics: NDB_24_Mar_2026_112347_AM_GSS_Bond_Framework.pdf
[39/104] Extracting metrics: NDB_06_Dec_2024_120131_PM_Trust_Deed_-_Basel_III_Compliant_Listed_Rated_Unsecured_Subordinated_Redeemable_Debenture_Issue_2024.pdf
[40/104] Extracting metrics: NDB_06_Dec_2024_120034_PM_Prospectus_-_Basel_III_Compliant_Listed_Rated_Unsecured_Subordinated_Redeemable_Debenture_Issue_2024.pdf
[41/104] Extracting metrics: NDB_23_Sep_2024_120000_AM_Trust_Deed_-_Basel_III_Compliant_Convertible_Debenture_Issue_2024.pdf
[42/104] Extracting metrics: NDB_24_Mar_2026_112119_AM_Prospectus.pdf
[43/104] Extracting metrics: NDB_07_Mar_2023_083141_AM_Annual_Report_2022_-_National_Development_Bank_PLC.pdf
[44/104] Extracting metrics: NDB_15_Mar_2021_085204_AM_National_Development_Bank_PLC_-_Annual_Report_2020.pdf
[45/104] Extracting metrics: NDB_04_Mar_2026_023916_PM_Annual_Report_as_at_31st_December_2025.pdf
[46/104] Extracting metrics: NDB_07_Mar_2022_084034_AM_Annual_Report_2021.pdf
[47/104] Extracting metrics: NDB_05_Mar_2025_023231_PM_Annual_Report_2024.pdf
[48/104] Extracting metrics: NDB_05_Mar_2024_084042_AM_Annual_Report_2023.pdf
[49/104] Extracting metrics: NDB_12_May_2023_044826_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2023.pdf
[50/104] Extracting metrics: NDB_14_May_2025_041238_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2025.pdf
[51/104] Extracting metrics: NDB_14_May_2024_031303_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2024.pdf
[52/104] Extracting metrics: NDB_04_Nov_2025_023242_PM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
[53/104] Extracting metrics: NDB_21_Feb_2023_034912_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2022.pdf
[54/104] Extracting metrics: NDB_14_Aug_2024_034851_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2024.pdf
[55/104] Extracting metrics: NDB_13_Nov_2024_031840_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2024.pdf
[56/104] Extracting metrics: NDB_14_Aug_2025_041749_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2025.pdf
[57/104] Extracting metrics: NDB_12_Nov_2021_033415_PM_Interim_Financial_Statements_30th_September_2021.pdf
[58/104] Extracting metrics: NDB_13_May_2022_035828_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2022.pdf
[59/104] Extracting metrics: NDB_13_May_2021_033428_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_1ST_QUARTER_ENDED_31_MARCH_2021.pdf
[60/104] Extracting metrics: NDB_20_Feb_2024_052044_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2023.pdf
[61/104] Extracting metrics: NDB_22_Feb_2022_033419_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2021.pdf
[62/104] Extracting metrics: NDB_20_Feb_2025_041558_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2024.pdf
[63/104] Extracting metrics: NDB_14_Nov_2023_034149_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2023.pdf
[64/104] Extracting metrics: NDB_18_Feb_2021_031522_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_4TH_QUARTER_ENDED_31_DECEMBER_2020.pdf
[65/104] Extracting metrics: NDB_15_Aug_2022_035221_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2022.pdf
[66/104] Extracting metrics: NDB_25_Feb_2026_034455_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
[67/104] Extracting metrics: NDB_30_Apr_2026_041330_PM_Interim_Financial_Statements_for_the_Quarter_ended_31st_March_2026.pdf
[68/104] Extracting metrics: NDB_14_Nov_2022_043208_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_3RD_QUARTER_ENDED_30_SEPTEMBER_2022.pdf
[69/104] Extracting metrics: NDB_28_Jul_2021_025633_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2021.pdf
[70/104] Extracting metrics: NDB_14_Aug_2023_035458_PM_INTERIM_FINANCIAL_STATEMENTS_FOR_THE_2ND_QUARTER_ENDED_30_JUNE_2023.pdf
[71/104] Extracting metrics: SAMP_22_Apr_2021_091601_AM_Trust_Deed_-_BASEL_III_Debenture_Issue_2021.pdf
[72/104] Extracting metrics: SAMP_22_Apr_2021_091507_AM_Prospectus_-_BASEL_III_Debenture_Issue_2021.pdf
[73/104] Extracting metrics: SAMP_15_Feb_2023_120538_PM_Supplementary_Trust_Deed_-_Basel_III_Debenture_Issue_2023.pdf
[74/104] Extracting metrics: SAMP_01_Apr_2025_101246_AM_Prospectus_-_BASEL_III_Compliant_Debenture_Issue_2025.pdf
[75/104] Extracting metrics: SAMP_15_Feb_2023_120136_PM_Prospectus_-_Basel_III_Debenture_Issue_2023.pdf
[76/104] Extracting metrics: SAMP_01_Apr_2025_101343_AM_Trust_Deed_-_BASEL_III_Compliant_Debenture_Issue_2025.pdf
[77/104] Extracting metrics: SAMP_15_Feb_2023_120245_PM_Trust_Deed_-_Basel_III_Debenture_Issue_2023.pdf
[78/104] Extracting metrics: SAMP_04_Mar_2025_023320_PM_Sampath_Bank_PLC_-_Annual_Report_2024.pdf
[79/104] Extracting metrics: SAMP_03_Mar_2023_032148_PM_Sampath_Bank_PLC_-_Annual_Report_2022.pdf
[80/104] Extracting metrics: SAMP_29_Feb_2024_044338_PM_Sampath_Bank_PLC_-_Annual_Report_2023.pdf
[81/104] Extracting metrics: SAMP_04_Mar_2026_025317_PM_Annual_Report_as_at_31st_December_2025.pdf
[82/104] Extracting metrics: SAMP_04_Mar_2022_040922_PM_Sampath_Bank_PLC_-_Annual_Report_2021.pdf
[83/104] Extracting metrics: SAMP_05_Mar_2021_023337_PM_Sampath_Bank_PLC_-_Annual_Report_2020.pdf
[84/104] Extracting metrics: SAMP_14_Aug_2025_082153_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2025.pdf
[85/104] Extracting metrics: SAMP_14_May_2025_050009_PM_Interim_Financial_Statements_for_the_period_ended_31st_March_2025.pdf
[86/104] Extracting metrics: SAMP_16_Feb_2021_114029_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2020.pdf
[87/104] Extracting metrics: SAMP_14_Nov_2023_083219_AM_Interim_Financial_Statements_for_the_period_ended_30th_September_2023.pdf
[88/104] Extracting metrics: SAMP_08_Aug_2024_082942_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2024.pdf
[89/104] Extracting metrics: SAMP_13_Aug_2021_084023_AM_Sampath_Bank_PLC_-_Interim_Financial_Statements_for_the_period_ended_30th_June_2021.pdf
[90/104] Extracting metrics: SAMP_12_Nov_2021_091415_AM_Interim_Financial_Statements_for_the_period_ended_30th_September_2021.pdf
[91/104] Extracting metrics: SAMP_13_Nov_2025_081726_AM_Interim_Financial_Statements_for_the_Quarter_ended_30th_September_2025.pdf
[92/104] Extracting metrics: SAMP_18_Feb_2025_083650_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2024.pdf
[93/104] Extracting metrics: SAMP_12_Aug_2022_085626_AM_Audited_Interim_Financial_Statements_for_the_period_ended_30th_June_2022.pdf
[94/104] Extracting metrics: SAMP_13_May_2022_083359_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2022.pdf
[95/104] Extracting metrics: SAMP_14_Aug_2023_083414_AM_Interim_Financial_Statements_for_the_period_ended_30th_June_2023.pdf
[96/104] Extracting metrics: SAMP_17_Feb_2023_095731_PM_Interim_Financial_Statements_for_the_year_ended_31st_December_2022.pdf
[97/104] Extracting metrics: SAMP_13_Nov_2024_044943_PM_Interim_Financial_Statements_for_the_period_ended_30th_September_2024.pdf
[98/104] Extracting metrics: SAMP_11_Nov_2022_085915_AM_Interim_Financial_Statements_as_of_30092022.pdf
[99/104] Extracting metrics: SAMP_20_Feb_2026_082839_AM_Interim_Financial_Statements_for_the_Quarter_ended_31st_December_2025.pdf
[100/104] Extracting metrics: SAMP_14_May_2024_084610_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2024.pdf
[101/104] Extracting metrics: SAMP_17_Feb_2022_083049_AM_Sampath_Bank_PLC_-_Interim_Financial_Statements_for_the_year_ended_31st_December_2021.pdf
[102/104] Extracting metrics: SAMP_12_May_2021_120000_AM_Interim_Financial_Statements_for_the_period_ended_31st_March_2021.pdf
[103/104] Extracting metrics: SAMP_15_May_2023_023450_PM_Interim_Financial_Statements_for_the_period_ended_31st_March_2023.pdf
[104/104] Extracting metrics: SAMP_15_Feb_2024_090043_AM_Interim_Financial_Statements_for_the_year_ended_31st_December_2023.pdf
Master metrics saved: cse_structured/financial_metrics_master.csv
Company metrics saved: cse_structured/company_wise/DOCK_COLOMBO_DOCKYARD_PLC_financial_metrics.csv
Company metrics saved: cse_structured/company_wise/NDB_NATIONAL_DEVELOPMENT_BANK_PLC_financial_metrics.csv
Company metrics saved: cse_structured/company_wise/SAMP_SAMPATH_BANK_PLC_financial_metrics.csv

In [ ]:
print(metrics_df.head())

print(metrics_df[[
    "company_folder",
    "report_type",
    "year",
    "quarter",
    "period",
    "revenue",
    "interest_income",
    "profit_before_tax",
    "profit_after_tax",
    "earnings_per_share",
    "total_assets"
]].head(20))

              company_folder report_type  \
0  DOCK_COLOMBO_DOCKYARD_PLC      annual
1  DOCK_COLOMBO_DOCKYARD_PLC      annual
2  DOCK_COLOMBO_DOCKYARD_PLC      annual
3  DOCK_COLOMBO_DOCKYARD_PLC      annual
4  DOCK_COLOMBO_DOCKYARD_PLC      annual

                                        pdf_filename  \
0  DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf
1  DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf
2  DOCK_30_Apr_2026_100702_PM_Audited_Financial_S...
3  DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annua...
4  DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf

                                            pdf_path  \
0  cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...
1  cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...
2  cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...
3  cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...
4  cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...

                                            txt_path  page_count  text_length  \
0  cse_extracted/texts/DOCK_COLOMBO_DOCKYARD_PLC/...         160       435999
1  cse_extracted/texts/DOCK_COLOMBO_DOCKYARD_PLC/...         112       301583
2  cse_extracted/texts/DOCK_COLOMBO_DOCKYARD_PLC/...          64       158029
3  cse_extracted/texts/DOCK_COLOMBO_DOCKYARD_PLC/...           5           90
4  cse_extracted/texts/DOCK_COLOMBO_DOCKYARD_PLC/...         132       373208

               period  year quarter  ...  interest_income  \
0  31st december 2023  2024      Q2  ...        -325194.0
1  31st december 2020  2020      Q2  ...        -244810.0
2       31 march 2026  2025      Q1  ...        -364984.0
3                None  2025    None  ...              NaN
4  31st december 2022  2023   Q4/FY  ...        -254401.0

   net_interest_income  total_operating_income  profit_before_tax  \
0                  NaN                -50216.0              31.00
1                  NaN                  5126.1               5.00
2                  NaN               -338452.0               1.01
3                  NaN                     NaN                NaN
4                  NaN              -1204740.0              31.00

   profit_after_tax  earnings_per_share  total_assets  total_liabilities  \
0             -12.0               -38.1       40310.0            37609.0
1           -1347.0               -16.1       15597.0            10377.0
2        -2741639.0              2024.0    38347971.0                NaN
3               NaN                 NaN           NaN                NaN
4             -33.0              -153.4       36049.0            35575.0

       equity  dividend_per_share
0   5490555.0                 0.0
1   7002778.0                 0.0
2  15501205.0                 NaN
3         NaN                 NaN
4   3290778.0                 0.0

[5 rows x 21 columns]
               company_folder report_type  year quarter               period  \
0   DOCK_COLOMBO_DOCKYARD_PLC      annual  2024      Q2   31st december 2023
1   DOCK_COLOMBO_DOCKYARD_PLC      annual  2020      Q2   31st december 2020
2   DOCK_COLOMBO_DOCKYARD_PLC      annual  2025      Q1        31 march 2026
3   DOCK_COLOMBO_DOCKYARD_PLC      annual  2025    None                 None
4   DOCK_COLOMBO_DOCKYARD_PLC      annual  2023   Q4/FY   31st december 2022
5   DOCK_COLOMBO_DOCKYARD_PLC      annual  2022   Q4/FY   31st december 2021
6   DOCK_COLOMBO_DOCKYARD_PLC      annual  2021   Q4/FY   31st december 2021
7   DOCK_COLOMBO_DOCKYARD_PLC     interim  2021   Q4/FY     31 december 2021
8   DOCK_COLOMBO_DOCKYARD_PLC     interim  2026   Q4/FY     31 december 2025
9   DOCK_COLOMBO_DOCKYARD_PLC     interim  2022      Q1        31 march 2022
10  DOCK_COLOMBO_DOCKYARD_PLC     interim  2023      Q2         30 june 2023
11  DOCK_COLOMBO_DOCKYARD_PLC     interim  2023      Q1        31 march 2023
12  DOCK_COLOMBO_DOCKYARD_PLC     interim  2025      Q3    30 september 2025
13  DOCK_COLOMBO_DOCKYARD_PLC     interim  2021      Q3    30 september 2021
14  DOCK_COLOMBO_DOCKYARD_PLC     interim  2026      Q1        31 march 2026
15  DOCK_COLOMBO_DOCKYARD_PLC     interim  2024   Q4/FY     31 december 2024
16  DOCK_COLOMBO_DOCKYARD_PLC     interim  2023      Q3  30th september 2023
17  DOCK_COLOMBO_DOCKYARD_PLC     interim  2022      Q2         30 june 2022
18  DOCK_COLOMBO_DOCKYARD_PLC     interim  2022      Q3    30 september 2022
19  DOCK_COLOMBO_DOCKYARD_PLC     interim  2025   Q4/FY     31 december 2025

       revenue  interest_income  profit_before_tax  profit_after_tax  \
0          7.0        -325194.0              31.00             -12.0
1       5010.0        -244810.0               5.00           -1347.0
2          5.0        -364984.0               1.01        -2741639.0
3          NaN              NaN                NaN               NaN
4      15863.0        -254401.0              31.00             -33.0
5      14585.0        -221662.0              31.00             516.0
6       9211.0              NaN                NaN               1.0
7    5434291.0        -242790.0          401416.00          344048.0
8    7528900.0              NaN                NaN         -475535.0
9    5571152.0         -46739.0          144873.00               NaN
10  11378259.0        -123250.0        -3033603.00        -2746480.0
11   9841508.0         -64399.0         -265163.00               NaN
12   7716538.0        -165072.0        -1954414.00        -2006350.0
13   4591064.0        -220921.0            1457.00          -32915.0
14   7609595.0        -364984.0        -2874717.00               NaN
15   6711810.0        -328101.0        -4524490.00         -860384.0
16   7918571.0        -192348.0        -9724881.00        -6713792.0
17   5106879.0        -110764.0          355556.00          192746.0
18   8147113.0        -166706.0          476975.00           86505.0
19   7528900.0        -276332.0        -2415089.00        -1924438.0

    earnings_per_share  total_assets
0               -38.10       40310.0
1               -16.10       15597.0
2              2024.00    38347971.0
3                  NaN           NaN
4              -153.40       36049.0
5                 9.60       48422.0
6                  NaN       24081.0
7                 4.75    27100811.0
8                -6.61           NaN
9                 1.60    33751883.0
10              -38.24    46936468.0
11               -4.50    50407428.0
12               -7.84    38749640.0
13               -0.57    25019886.0
14               -1.32    38347972.0
15              -11.96    43892946.0
16              -93.50    43118918.0
17                2.61    42228958.0
18                1.20    44917792.0
19              -26.69    37384862.0

### LLM Extraction

In [ ]:
! pip install google-genai -q

In [ ]:
import os

os.environ["GEMINI_API_KEY"] = "AIzaSyCNQuQ2KtpvBYCX-Rdn54KLTQYvJ7AeFAU"

In [ ]:
import os
import re
import json
import time
import pandas as pd
from google import genai
from google.genai import types

INPUT_CSV = "cse_extracted/extracted_pdf_text.csv"
OUTPUT_CSV = "cse_structured/financial_metrics_gemini_validated.csv"

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

def normalize_text(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text)
    return text

def extract_relevant_snippets(text, window=1800):
    keywords = [
        "statement of profit or loss",
        "income statement",
        "profit after tax",
        "profit before tax",
        "net profit after tax",
        "earnings per share",
        "interest income",
        "net interest income",
        "total operating income",
        "total assets",
        "total liabilities",
        "statement of financial position",
        "financial position"
    ]

    text_norm = normalize_text(text)
    text_lower = text_norm.lower()

    snippets = []

    for kw in keywords:
        idx = text_lower.find(kw)
        if idx != -1:
            start = max(0, idx - window)
            end = min(len(text_norm), idx + window)
            snippets.append(text_norm[start:end])

    # remove duplicates roughly
    unique = []
    seen = set()

    for s in snippets:
        key = s[:300]
        if key not in seen:
            unique.append(s)
            seen.add(key)

    return "\n\n--- SNIPPET ---\n\n".join(unique[:6])

schema = {
    "type": "object",
    "properties": {
        "company_name": {"type": "string"},
        "report_type": {"type": "string"},
        "period_end": {"type": "string"},
        "financial_year": {"type": "string"},
        "quarter": {"type": "string"},
        "currency": {"type": "string"},
        "scale": {"type": "string"},
        "revenue": {"type": ["number", "null"]},
        "interest_income": {"type": ["number", "null"]},
        "net_interest_income": {"type": ["number", "null"]},
        "total_operating_income": {"type": ["number", "null"]},
        "profit_before_tax": {"type": ["number", "null"]},
        "profit_after_tax": {"type": ["number", "null"]},
        "earnings_per_share": {"type": ["number", "null"]},
        "total_assets": {"type": ["number", "null"]},
        "total_liabilities": {"type": ["number", "null"]},
        "equity": {"type": ["number", "null"]},
        "confidence": {"type": "number"},
        "validation_notes": {"type": "string"}
    },
    "required": [
        "company_name",
        "report_type",
        "period_end",
        "financial_year",
        "quarter",
        "currency",
        "scale",
        "revenue",
        "interest_income",
        "net_interest_income",
        "total_operating_income",
        "profit_before_tax",
        "profit_after_tax",
        "earnings_per_share",
        "total_assets",
        "total_liabilities",
        "equity",
        "confidence",
        "validation_notes"
    ]
}

def validate_with_gemini(row):
    text = row["extracted_text"]
    snippets = extract_relevant_snippets(text)

    prompt = f"""
You are validating financial metrics extracted from a Sri Lankan listed company financial report.

Use ONLY the text snippets provided.
Do not guess missing values.
If a value is not clearly available, return null.

Important:
- Identify whether numbers are in Rs, Rs. Mn, LKR million, or another scale.
- Prefer current period/current year values.
- Ignore chart axis labels unless clearly part of a table.
- For banks, revenue may not be available; use interest_income, net_interest_income, or total_operating_income.
- Return numeric values exactly in the scale stated by the report.
- Explain uncertainty in validation_notes.

File name: {row.get("pdf_filename")}
Folder company: {row.get("company_folder")}
Report type from folder: {row.get("report_type")}

TEXT SNIPPETS:
{snippets}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_json_schema=schema,
            temperature=0
        )
    )

    return json.loads(response.text)

def run_gemini_validation(limit=None):
    extracted_df = pd.read_csv(INPUT_CSV)

    success_df = extracted_df[
        extracted_df["extraction_status"].astype(str).str.lower().eq("success")
    ].copy()

    if limit:
        success_df = success_df.head(limit)

    results = []

    for i, (_, row) in enumerate(success_df.iterrows(), start=1):
        print(f"[{i}/{len(success_df)}] Validating:", row["pdf_filename"])

        try:
            llm_result = validate_with_gemini(row)

            record = {
                "company_folder": row["company_folder"],
                "report_type_folder": row["report_type"],
                "pdf_filename": row["pdf_filename"],
                "pdf_path": row["pdf_path"],
                **llm_result
            }

        except Exception as e:
            record = {
                "company_folder": row.get("company_folder", ""),
                "report_type_folder": row.get("report_type", ""),
                "pdf_filename": row.get("pdf_filename", ""),
                "pdf_path": row.get("pdf_path", ""),
                "error": str(e)
            }

        results.append(record)
        time.sleep(1)

    validated_df = pd.DataFrame(results)
    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)
    validated_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

    print("Saved:", OUTPUT_CSV)
    return validated_df

In [ ]:
validated_df = run_gemini_validation(limit=5)
validated_df.head()

[1/5] Validating: DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf
[2/5] Validating: DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf
[3/5] Validating: DOCK_30_Apr_2026_100702_PM_Audited_Financial_Statements_for_the_Period_ended_31st_March_2026.pdf
[4/5] Validating: DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annual_Report_2024.pdf
[5/5] Validating: DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf
Saved: cse_structured/financial_metrics_gemini_validated.csv

,company_folder,report_type_folder,pdf_filename,pdf_path,company_name,report_type,period_end,financial_year,quarter,currency,...,net_interest_income,total_operating_income,profit_before_tax,profit_after_tax,earnings_per_share,total_assets,total_liabilities,equity,confidence,validation_notes
0,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,"31 December, 2024",2024,Full Year,LKR,...,None,None,NaN,-2743.0,-38.10,43860.7,38370.1,5311.3,1.0,"All financial figures are for the Group, as pr..."
1,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,2020-12-31,2020,null,LKR,...,None,None,NaN,-1161.1,-16.10,18056.0,11053.2,6918.3,1.0,All financial figures (except Earnings Per Sha...
2,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_30_Apr_2026_100702_PM_Audited_Financial_S...,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,COLOMBO DOCKYARD PLC,annual,2026-03-31,2026,Annual,LKR,...,None,None,-2874717.0,-2920728.0,-11.34,38347971.0,22846766.0,15501205.0,5.0,Revenue and Total Operating Income were not ex...
3,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annua...,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,COLOMBO DOCKYARD PLC,annual,null,2024,null,null,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,0.0,No text snippets were provided to extract fina...
4,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,2023-12-31,2023,Full Year,LKR,...,None,None,-13578.0,-11127.0,-153.00,36049.0,35575.0,473.0,0.9,Financial figures are primarily extracted from...

In [ ]:
# validation of regex and llm extraction

# Use Gemini values when confidence >= 0.7
# Flag rows with confidence < 0.7 for manual review
# Exclude errata / very short PDFs from analysis

In [ ]:
import pandas as pd
import os

INPUT = "cse_structured/financial_metrics_gemini_validated.csv"
OUTPUT = "cse_structured/financial_metrics_clean_validated.csv"

df = pd.read_csv(INPUT)

# Convert confidence to numeric
df["confidence"] = pd.to_numeric(df["confidence"], errors="coerce").fillna(0)

# Remove low-confidence rows and non-financial/errata-like reports
clean_df = df[
    (df["confidence"] >= 0.7) &
    (~df["pdf_filename"].str.lower().str.contains("errata|correction|notice", na=False))
].copy()

# Sort by company and year
clean_df["financial_year"] = pd.to_numeric(clean_df["financial_year"], errors="coerce")
clean_df = clean_df.sort_values(
    ["company_folder", "financial_year", "quarter"],
    na_position="last"
)

clean_df.to_csv(OUTPUT, index=False, encoding="utf-8-sig")

print("Original rows:", len(df))
print("Clean rows:", len(clean_df))
print("Saved:", OUTPUT)

clean_df.head()

Original rows: 5
Clean rows: 4
Saved: cse_structured/financial_metrics_clean_validated.csv

,company_folder,report_type_folder,pdf_filename,pdf_path,company_name,report_type,period_end,financial_year,quarter,currency,...,net_interest_income,total_operating_income,profit_before_tax,profit_after_tax,earnings_per_share,total_assets,total_liabilities,equity,confidence,validation_notes
1,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_12_Apr_2021_041705_PM_Annual_Report_2020.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,2020-12-31,2020,NaN,LKR,...,NaN,NaN,NaN,-1161.1,-16.10,18056.0,11053.2,6918.3,1.0,All financial figures (except Earnings Per Sha...
4,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_03_Jun_2024_090601_AM_Annual_Report_2023.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,2023-12-31,2023,Full Year,LKR,...,NaN,NaN,-13578.0,-11127.0,-153.00,36049.0,35575.0,473.0,0.9,Financial figures are primarily extracted from...
0,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_06_Jun_2025_045407_PM_Annual_Report_2024.pdf,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,Colombo Dockyard PLC,Annual Report,"31 December, 2024",2024,Full Year,LKR,...,NaN,NaN,NaN,-2743.0,-38.10,43860.7,38370.1,5311.3,1.0,"All financial figures are for the Group, as pr..."
2,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_30_Apr_2026_100702_PM_Audited_Financial_S...,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,COLOMBO DOCKYARD PLC,annual,2026-03-31,2026,Annual,LKR,...,NaN,NaN,-2874717.0,-2920728.0,-11.34,38347971.0,22846766.0,15501205.0,5.0,Revenue and Total Operating Income were not ex...

In [ ]:
REVIEW_OUTPUT = "cse_structured/financial_metrics_manual_review.csv"

review_df = df[
    (df["confidence"] < 0.7) |
    (df["pdf_filename"].str.lower().str.contains("errata|correction|notice", na=False))
].copy()

review_df.to_csv(REVIEW_OUTPUT, index=False, encoding="utf-8-sig")

print("Manual review rows:", len(review_df))
print("Saved:", REVIEW_OUTPUT)

Manual review rows: 1
Saved: cse_structured/financial_metrics_manual_review.csv

In [ ]:
review_df.head()

,company_folder,report_type_folder,pdf_filename,pdf_path,company_name,report_type,period_end,financial_year,quarter,currency,...,net_interest_income,total_operating_income,profit_before_tax,profit_after_tax,earnings_per_share,total_assets,total_liabilities,equity,confidence,validation_notes
3,DOCK_COLOMBO_DOCKYARD_PLC,annual,DOCK_20_Jun_2025_053719_PM_Errata_to_the_Annua...,cse_reports/DOCK_COLOMBO_DOCKYARD_PLC/annual/D...,COLOMBO DOCKYARD PLC,annual,NaN,2024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,No text snippets were provided to extract fina...

In [ ]:
# ==============================
# 🔽 PASTE YOUR JSON HERE
# ==============================
COMPANY_JSON = [
{
"company_name": "John Keells Holdings PLC",
"cse_symbol": "JKH.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=JKH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 1,
"total_batches_estimated": 6,
"continue_from_symbol": "KHL.N0000"
},
{
"company_name": "Commercial Bank of Ceylon PLC",
"cse_symbol": "COMB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=COMB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hatton National Bank PLC",
"cse_symbol": "HNB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HNB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sampath Bank PLC",
"cse_symbol": "SAMP.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SAMP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "National Development Bank PLC",
"cse_symbol": "NDB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=NDB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "DFCC Bank PLC",
"cse_symbol": "DFCC.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DFCC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Nations Trust Bank PLC",
"cse_symbol": "NTB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=NTB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Seylan Bank PLC",
"cse_symbol": "SEYB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SEYB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Pan Asia Banking Corporation PLC",
"cse_symbol": "PABC.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PABC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Amana Bank PLC",
"cse_symbol": "ABL.N0000",
"board": "Second Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ABL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dialog Axiata PLC",
"cse_symbol": "DIAL.N0000",
"board": "Main Board",
"sector": "Telecommunication Services",
"industry_group": "Telecommunication Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DIAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sri Lanka Telecom PLC",
"cse_symbol": "SLTL.N0000",
"board": "Main Board",
"sector": "Telecommunication Services",
"industry_group": "Telecommunication Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SLTL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka IOC PLC",
"cse_symbol": "LIOC.N0000",
"board": "Main Board",
"sector": "Energy",
"industry_group": "Energy",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LIOC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Melstacorp PLC",
"cse_symbol": "MELS.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MELS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Distilleries Company of Sri Lanka PLC",
"cse_symbol": "DIST.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DIST.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Carson Cumberbatch PLC",
"cse_symbol": "CARS.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CARS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Bukit Darah PLC",
"cse_symbol": "BUKI.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BUKI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Tobacco Company PLC",
"cse_symbol": "CTC.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CTC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Milk Foods (CWE) PLC",
"cse_symbol": "LMF.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LMF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Cold Stores PLC",
"cse_symbol": "CCS.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CCS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Keells Food Products PLC",
"cse_symbol": "KFP.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KFP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Watawala Plantations PLC",
"cse_symbol": "WATA.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=WATA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hayleys PLC",
"cse_symbol": "HAYL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HAYL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Aitken Spence PLC",
"cse_symbol": "SPEN.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SPEN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Richard Pieris and Company PLC",
"cse_symbol": "RICH.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RICH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Softlogic Holdings PLC",
"cse_symbol": "SHL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Vallibel One PLC",
"cse_symbol": "VONE.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=VONE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Royal Ceramics Lanka PLC",
"cse_symbol": "RCL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RCL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Access Engineering PLC",
"cse_symbol": "AEL.N0000",
"board": "Second Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AEL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hemas Holdings PLC",
"cse_symbol": "HHL.N0000",
"board": "Main Board",
"sector": "Household & Personal Products",
"industry_group": "Household & Personal Products",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "LOLC Holdings PLC",
"cse_symbol": "LOLC.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LOLC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "LB Finance PLC",
"cse_symbol": "LFIN.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LFIN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Central Finance Company PLC",
"cse_symbol": "CFIN.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CFIN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Commercial Credit and Finance PLC",
"cse_symbol": "COCR.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=COCR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "People's Leasing & Finance PLC",
"cse_symbol": "PLC.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PLC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylinco Insurance PLC",
"cse_symbol": "CINS.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CINS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Singer (Sri Lanka) PLC",
"cse_symbol": "SINS.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SINS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Chevron Lubricants Lanka PLC",
"cse_symbol": "LLUB.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LLUB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Tokyo Cement Company (Lanka) PLC",
"cse_symbol": "TKYO.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TKYO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Asiri Hospital Holdings PLC",
"cse_symbol": "ASIR.N0000",
"board": "Second Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ASIR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Nawaloka Hospitals PLC",
"cse_symbol": "NHL.N0000",
"board": "Main Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=NHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kelani Tyres PLC",
"cse_symbol": "TYRE.N0000",
"board": "Main Board",
"sector": "Automobiles & Components",
"industry_group": "Automobiles & Components",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TYRE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Teejay Lanka PLC",
"cse_symbol": "TJL.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TJL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Windforce PLC",
"cse_symbol": "WIND.N0000",
"board": "Main Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=WIND.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Vidullanka PLC",
"cse_symbol": "VLL.N0000",
"board": "Main Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=VLL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Aitken Spence Hotel Holdings PLC",
"cse_symbol": "AHUN.N0000",
"board": "Second Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AHUN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Asian Hotels and Properties PLC",
"cse_symbol": "AHPL.N0000",
"board": "Second Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AHPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Taj Lanka Hotels PLC",
"cse_symbol": "TAJ.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TAJ.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Galadari Hotels (Lanka) PLC",
"cse_symbol": "GHLL.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GHLL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "John Keells Hotels PLC",
"cse_symbol": "KHL.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Browns Investments PLC",
"cse_symbol": "BIL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BIL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 2,
"total_batches_estimated": 6,
"continue_from_symbol": "SIRA.N0000"
},
{
"company_name": "Brown & Company PLC",
"cse_symbol": "BRWN.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BRWN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Tiles PLC",
"cse_symbol": "TILE.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TILE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Walltiles PLC",
"cse_symbol": "LWL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LWL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dipped Products PLC",
"cse_symbol": "DIPD.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DIPD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Haycarb PLC",
"cse_symbol": "HAYC.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HAYC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kelani Valley Plantations PLC",
"cse_symbol": "KVAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KVAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Talawakelle Tea Estates PLC",
"cse_symbol": "TTE.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TTE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Elpitiya Plantations PLC",
"cse_symbol": "ELPI.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ELPI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kegalle Plantations PLC",
"cse_symbol": "KGAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KGAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Namunukula Plantations PLC",
"cse_symbol": "NAMU.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=NAMU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Balangoda Plantations PLC",
"cse_symbol": "BALA.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BALA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Bogawantalawa Tea Estates PLC",
"cse_symbol": "BOPL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BOPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kotagala Plantations PLC",
"cse_symbol": "KOTA.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KOTA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Agalawatte Plantations PLC",
"cse_symbol": "AGAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AGAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Malwatte Valley Plantations PLC",
"cse_symbol": "MAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Maskeliya Plantations PLC",
"cse_symbol": "MASK.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MASK.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hapugastenne Plantations PLC",
"cse_symbol": "HAPU.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HAPU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Udapussellawa Plantations PLC",
"cse_symbol": "UDAP.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UDAP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sunshine Holdings PLC",
"cse_symbol": "SUN.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SUN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "CIC Holdings PLC",
"cse_symbol": "CIC.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CIC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Chemanex PLC",
"cse_symbol": "CHMX.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CHMX.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Union Bank of Colombo PLC",
"cse_symbol": "UBC.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UBC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sanasa Development Bank PLC",
"cse_symbol": "SDB.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SDB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Housing Development Finance Corporation Bank of Sri Lanka",
"cse_symbol": "HDFC.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HDFC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Mercantile Investments and Finance PLC",
"cse_symbol": "MERC.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MERC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Alliance Finance Company PLC",
"cse_symbol": "ALLI.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ALLI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Citizens Development Business Finance PLC",
"cse_symbol": "CDB.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CDB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "LOLC Finance PLC",
"cse_symbol": "LOFC.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LOFC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Vallibel Finance PLC",
"cse_symbol": "VFIN.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=VFIN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Senkadagala Finance PLC",
"cse_symbol": "SFCL.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SFCL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "HNB Finance PLC",
"cse_symbol": "HNBF.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HNBF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Orient Finance PLC",
"cse_symbol": "ORIN.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ORIN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Prime Lands Residencies PLC",
"cse_symbol": "PLR.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PLR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Overseas Realty (Ceylon) PLC",
"cse_symbol": "OSEA.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=OSEA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Colombo Land and Development Company PLC",
"cse_symbol": "CLND.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CLND.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "C T Holdings PLC",
"cse_symbol": "CTHR.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CTHR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Cargills (Ceylon) PLC",
"cse_symbol": "CARG.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CARG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lion Brewery (Ceylon) PLC",
"cse_symbol": "LION.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LION.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Bairaha Farms PLC",
"cse_symbol": "BFL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BFL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Three Acre Farms PLC",
"cse_symbol": "TAFL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TAFL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Grain Elevators PLC",
"cse_symbol": "GRAN.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GRAN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hela Apparel Holdings PLC",
"cse_symbol": "HELA.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HELA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hayleys Fabric PLC",
"cse_symbol": "MGT.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MGT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Printcare PLC",
"cse_symbol": "CARE.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CARE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "BPPL Holdings PLC",
"cse_symbol": "BPPL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BPPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Alumex PLC",
"cse_symbol": "ALUM.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ALUM.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Aluminum Industries PLC",
"cse_symbol": "LALU.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LALU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "ACL Cables PLC",
"cse_symbol": "ACL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ACL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kelani Cables PLC",
"cse_symbol": "KCAB.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KCAB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Softlogic Life Insurance PLC",
"cse_symbol": "AAIC.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AAIC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 3,
"total_batches_estimated": 6,
"continue_from_symbol": "LHL.N0000"
},
{
"company_name": "Janashakthi Insurance PLC",
"cse_symbol": "JINS.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=JINS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "HNB Assurance PLC",
"cse_symbol": "HASU.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HASU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Union Assurance PLC",
"cse_symbol": "UAL.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Amana Takaful PLC",
"cse_symbol": "ATL.N0000",
"board": "Dirisavi Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ATL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Amana Takaful Life PLC",
"cse_symbol": "ATLL.N0000",
"board": "Dirisavi Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ATLL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Arpico Insurance PLC",
"cse_symbol": "AINS.N0000",
"board": "Dirisavi Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AINS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "People's Insurance PLC",
"cse_symbol": "PINS.N0000",
"board": "Main Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PINS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Co-operative Insurance Company PLC",
"cse_symbol": "COOP.N0000",
"board": "Dirisavi Board",
"sector": "Insurance",
"industry_group": "Insurance",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=COOP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Vallibel Power Erathna PLC",
"cse_symbol": "VPEL.N0000",
"board": "Main Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=VPEL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Panasian Power PLC",
"cse_symbol": "PAP.N0000",
"board": "Main Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PAP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Resus Energy PLC",
"cse_symbol": "HPWR.N0000",
"board": "Main Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HPWR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "LVL Energy Fund PLC",
"cse_symbol": "LVEF.N0000",
"board": "Dirisavi Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LVEF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Ventures PLC",
"cse_symbol": "LVEN.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LVEN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lotus Hydro Power PLC",
"cse_symbol": "HPFL.N0000",
"board": "Dirisavi Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HPFL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Horana Plantations PLC",
"cse_symbol": "HOPL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HOPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kahawatte Plantations PLC",
"cse_symbol": "KAHA.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KAHA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Madulsima Plantations PLC",
"cse_symbol": "MADU.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MADU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Agarapatana Plantations PLC",
"cse_symbol": "AGPL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AGPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Asiri Surgical Hospital PLC",
"cse_symbol": "AMSL.N0000",
"board": "Main Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AMSL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "The Lanka Hospitals Corporation PLC",
"cse_symbol": "LHCL.N0000",
"board": "Main Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LHCL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Hospitals PLC",
"cse_symbol": "CHL.N0000",
"board": "Main Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Singhe Hospitals PLC",
"cse_symbol": "SINH.N0000",
"board": "Dirisavi Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SINH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "E - Channelling PLC",
"cse_symbol": "ECL.N0000",
"board": "Dirisavi Board",
"sector": "Health Care Equipment & Services",
"industry_group": "Health Care Equipment & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ECL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Renuka Foods PLC",
"cse_symbol": "COCO.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=COCO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Renuka Agri Foods PLC",
"cse_symbol": "RAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Convenience Foods (Lanka) PLC",
"cse_symbol": "SOY.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SOY.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Tea Brokers PLC",
"cse_symbol": "CTBL.N0000",
"board": "Dirisavi Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CTBL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Harischandra Mills PLC",
"cse_symbol": "HARI.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HARI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kotmale Holdings PLC",
"cse_symbol": "LAMB.N0000",
"board": "Dirisavi Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LAMB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Ceramic PLC",
"cse_symbol": "CERA.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CERA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sierra Cables PLC",
"cse_symbol": "SIRA.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SIRA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Swisstek (Ceylon) PLC",
"cse_symbol": "PARQ.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PARQ.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ambeon Capital PLC",
"cse_symbol": "TAP.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TAP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ambeon Holdings PLC",
"cse_symbol": "GREG.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GREG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "The Colombo Fort Land and Building PLC",
"cse_symbol": "CFLD.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CFLD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Mahaweli Reach Hotels PLC",
"cse_symbol": "MRH.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MRH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Marawila Resorts PLC",
"cse_symbol": "MARA.N0000",
"board": "Dirisavi Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MARA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sigiriya Village Hotels PLC",
"cse_symbol": "SIGV.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SIGV.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Beruwala Resorts PLC",
"cse_symbol": "BERU.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BERU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Eden Hotel Lanka PLC",
"cse_symbol": "EDEN.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=EDEN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hunas Holdings PLC",
"cse_symbol": "HUNA.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HUNA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dolphin Hotels PLC",
"cse_symbol": "KEEH.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KEEH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Serendib Hotels PLC",
"cse_symbol": "SHOT.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SHOT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Pegasus Hotels of Ceylon PLC",
"cse_symbol": "PEG.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PEG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ramboda Falls PLC",
"cse_symbol": "RFL.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RFL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Royal Palms Beach Hotels PLC",
"cse_symbol": "RPBH.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RPBH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Tangerine Beach Hotels PLC",
"cse_symbol": "TANG.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TANG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Amaya Leisure PLC",
"cse_symbol": "CONN.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CONN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Jetwing Symphony PLC",
"cse_symbol": "JETS.N0000",
"board": "Dirisavi Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=JETS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lighthouse Hotel PLC",
"cse_symbol": "LHL.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 4,
"total_batches_estimated": 6,
"continue_from_symbol": "SELI.N0000"
},
{
"company_name": "Nuwara Eliya Hotels PLC",
"cse_symbol": "NEH.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=NEH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Trans Asia Hotels PLC",
"cse_symbol": "TRAN.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TRAN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Citrus Leisure PLC",
"cse_symbol": "REEF.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=REEF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hikkaduwa Beach Resort PLC",
"cse_symbol": "CITH.N0000",
"board": "Dirisavi Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CITH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Waskaduwa Beach Resort PLC",
"cse_symbol": "CITW.N0000",
"board": "Dirisavi Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CITW.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "The Kingsbury PLC",
"cse_symbol": "SERV.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SERV.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Browns Beach Hotels PLC",
"cse_symbol": "BBH.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BBH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Palm Garden Hotels PLC",
"cse_symbol": "PALM.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PALM.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Bogala Graphite Lanka PLC",
"cse_symbol": "BOGA.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BOGA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Chrissworld PLC",
"cse_symbol": "CWL.N0000",
"board": "Empower Board",
"sector": "Transportation",
"industry_group": "Transportation",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CWL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Realty Investments PLC",
"cse_symbol": "ASCO.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ASCO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "C T Land Development PLC",
"cse_symbol": "CTLD.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CTLD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Equity Two PLC",
"cse_symbol": "ETWO.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ETWO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Serendib Land PLC",
"cse_symbol": "SLND.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SLND.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "York Arcade Holdings PLC",
"cse_symbol": "YORK.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=YORK.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lee Hedges PLC",
"cse_symbol": "SHAW.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SHAW.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "On'ally Holdings PLC",
"cse_symbol": "ONAL.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ONAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Commercial Development Company PLC",
"cse_symbol": "COMD.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=COMD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Millennium Housing Developers PLC",
"cse_symbol": "MHD.N0000",
"board": "Dirisavi Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MHD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kelsey Developments PLC",
"cse_symbol": "KDL.N0000",
"board": "Dirisavi Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KDL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Asia Asset Finance PLC",
"cse_symbol": "AAF.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AAF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Asia Capital PLC",
"cse_symbol": "ACAP.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ACAP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Capital Alliance PLC",
"cse_symbol": "CALT.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CALT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "First Capital Holdings PLC",
"cse_symbol": "CFVF.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CFVF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "First Capital Treasuries PLC",
"cse_symbol": "FCT.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=FCT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sarvodaya Development Finance PLC",
"cse_symbol": "SDF.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SDF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "SMB Finance PLC",
"cse_symbol": "SEMB.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SEMB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Shaw Wallace Investments PLC",
"cse_symbol": "KZOO.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KZOO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Merchant Bank of Sri Lanka & Finance PLC",
"cse_symbol": "MBSL.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MBSL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "People's Merchant Finance PLC",
"cse_symbol": "PMB.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PMB.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Multi Finance PLC",
"cse_symbol": "MFL.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MFL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Nation Lanka Finance PLC",
"cse_symbol": "CSF.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CSF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Softlogic Finance PLC",
"cse_symbol": "CRL.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CRL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Associated Motor Finance Company PLC",
"cse_symbol": "AMF.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AMF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Investment PLC",
"cse_symbol": "CINV.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CINV.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Guardian Investment Trust PLC",
"cse_symbol": "GUAR.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GUAR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Renuka Holdings PLC",
"cse_symbol": "RHL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Abans Electricals PLC",
"cse_symbol": "ABAN.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ABAN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Singer Industries (Ceylon) PLC",
"cse_symbol": "SINI.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SINI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Regnis (Lanka) PLC",
"cse_symbol": "REG.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=REG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dankotuwa Porcelain PLC",
"cse_symbol": "DPL.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lankem Ceylon PLC",
"cse_symbol": "LCEY.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LCEY.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "E B Creasy and Company PLC",
"cse_symbol": "EBCR.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=EBCR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "C. W. Mackie PLC",
"cse_symbol": "CWM.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CWM.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Laugfs Gas PLC",
"cse_symbol": "LGL.N0000",
"board": "Main Board",
"sector": "Energy",
"industry_group": "Energy",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LGL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Radiant Gems International PLC",
"cse_symbol": "RGEM.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RGEM.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Muller and Phipps (Ceylon) PLC",
"cse_symbol": "MULL.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MULL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Good Hope PLC",
"cse_symbol": "GOOD.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GOOD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Indo-Malay PLC",
"cse_symbol": "INDO.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=INDO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Selinsing PLC",
"cse_symbol": "SELI.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SELI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 5,
"total_batches_estimated": 6,
"continue_from_symbol": "MDL.N0000"
},
{
"company_name": "Shalimar (Malay) PLC",
"cse_symbol": "SHAL.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SHAL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Autodrome PLC",
"cse_symbol": "AUTO.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AUTO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Ashok Leyland PLC",
"cse_symbol": "ASHO.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ASHO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Diesel & Motor Engineering PLC",
"cse_symbol": "DIMO.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DIMO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Sathosa Motors PLC",
"cse_symbol": "SMOT.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SMOT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "United Motors Lanka PLC",
"cse_symbol": "UML.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UML.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "C. M. Holdings PLC",
"cse_symbol": "CMH.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CMH.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "R I L Property PLC",
"cse_symbol": "RIL.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RIL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Blue Diamonds Jewellery Worldwide PLC",
"cse_symbol": "BLUE.N0000",
"board": "Main Board",
"sector": "Consumer Durables & Apparel",
"industry_group": "Consumer Durables & Apparel",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BLUE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hunter & Company PLC",
"cse_symbol": "HUNT.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HUNT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Printers PLC",
"cse_symbol": "CPRT.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CPRT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Paragon Ceylon PLC",
"cse_symbol": "PARA.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PARA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Gestetner of Ceylon PLC",
"cse_symbol": "GEST.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=GEST.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Odel PLC",
"cse_symbol": "ODEL.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ODEL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Eastern Merchants PLC",
"cse_symbol": "EMER.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=EMER.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Agstar PLC",
"cse_symbol": "AGST.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AGST.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Colombo City Holdings PLC",
"cse_symbol": "PHAR.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PHAR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Cargo Boat Development Company PLC",
"cse_symbol": "CABO.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CABO.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Renuka City Hotels PLC",
"cse_symbol": "RENU.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=RENU.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Anilana Hotels and Properties PLC",
"cse_symbol": "ALHP.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ALHP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Hotel Sigiriya PLC",
"cse_symbol": "HSIG.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HSIG.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Bansei Royal Resorts Hikkaduwa PLC",
"cse_symbol": "BRR.N0000",
"board": "Dirisavi Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=BRR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "JAT Holdings PLC",
"cse_symbol": "JAT.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=JAT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "hSenid Business Solutions PLC",
"cse_symbol": "HBS.N0000",
"board": "Dirisavi Board",
"sector": "Software & Services",
"industry_group": "Software & Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HBS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "UB Finance Company PLC",
"cse_symbol": "UBF.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UBF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Lanka Credit and Business Finance PLC",
"cse_symbol": "LCBF.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LCBF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Singer Finance (Lanka) PLC",
"cse_symbol": "SFIN.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SFIN.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dialog Finance PLC",
"cse_symbol": "CALF.N0000",
"board": "Dirisavi Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CALF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Standard Capital PLC",
"cse_symbol": "SING.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SING.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Tess Agro PLC",
"cse_symbol": "TESS.N0000",
"board": "Dirisavi Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TESS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Mahaweli Coconut Plantations PLC",
"cse_symbol": "MCPL.N0000",
"board": "Dirisavi Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MCPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Laugfs Power PLC",
"cse_symbol": "LPL.N0000",
"board": "Dirisavi Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LPL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kapruka Holdings PLC",
"cse_symbol": "KPHL.N0000",
"board": "Main Board",
"sector": "Retailing",
"industry_group": "Retailing",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KPHL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Seylan Developments PLC",
"cse_symbol": "CSD.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CSD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Property Development PLC",
"cse_symbol": "PDL.N0000",
"board": "Main Board",
"sector": "Real Estate",
"industry_group": "Real Estate",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PDL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Colombo Investment Trust PLC",
"cse_symbol": "CIT.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CIT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Colombo Fort Investments PLC",
"cse_symbol": "CFI.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CFI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ex-pack Corrugated Cartons PLC",
"cse_symbol": "PACK.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=PACK.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Richard Pieris Exports PLC",
"cse_symbol": "REXP.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=REXP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Mercantile Shipping Company PLC",
"cse_symbol": "MSL.N0000",
"board": "Main Board",
"sector": "Transportation",
"industry_group": "Transportation",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MSL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Aitken Spence Plantation Managements PLC",
"cse_symbol": "ASPM.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ASPM.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "MTD Walkers PLC",
"cse_symbol": "KAPI.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KAPI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Dilmah Ceylon Tea Company PLC",
"cse_symbol": "CTEA.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CTEA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Colombo Dockyard PLC",
"cse_symbol": "DOCK.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=DOCK.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Swadeshi Industrial Works PLC",
"cse_symbol": "SWAD.N0000",
"board": "Main Board",
"sector": "Household & Personal Products",
"industry_group": "Household & Personal Products",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SWAD.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Office Equipment PLC",
"cse_symbol": "OFEQ.N0000",
"board": "Main Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=OFEQ.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Ceylon Hotels Corporation PLC",
"cse_symbol": "CHOT.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CHOT.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Kandy Hotels Company (1938) PLC",
"cse_symbol": "KHC.N0000",
"board": "Main Board",
"sector": "Consumer Services",
"industry_group": "Consumer Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=KHC.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "ACL Plastics PLC",
"cse_symbol": "APLA.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=APLA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "HVA Foods PLC",
"cse_symbol": "HVA.N0000",
"board": "Dirisavi Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=HVA.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01",
"batch_number": 6,
"total_batches_estimated": 6,
"continue_from_symbol": None
},
{
"company_name": "Lankem Developments PLC",
"cse_symbol": "LDEV.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LDEV.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Central Industries PLC",
"cse_symbol": "CIND.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CIND.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Laxapana Batteries PLC",
"cse_symbol": "LITE.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LITE.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Mackwoods Energy PLC",
"cse_symbol": "MEL.N0000",
"board": "Dirisavi Board",
"sector": "Utilities",
"industry_group": "Utilities",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MEL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Tea Smallholder Factories PLC",
"cse_symbol": "TSML.N0000",
"board": "Main Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=TSML.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Alpha Fire Services PLC",
"cse_symbol": "AFS.N0000",
"board": "Empower Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=AFS.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "E M L Consultants PLC",
"cse_symbol": "EML.N0000",
"board": "Empower Board",
"sector": "Commercial & Professional Services",
"industry_group": "Commercial & Professional Services",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=EML.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Luminex PLC",
"cse_symbol": "LUMX.N0000",
"board": "Empower Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=LUMX.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Unisyst Engineering PLC",
"cse_symbol": "ALUF.N0000",
"board": "Main Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=ALUF.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Softlogic Capital PLC",
"cse_symbol": "SCAP.N0000",
"board": "Main Board",
"sector": "Diversified Financials",
"industry_group": "Diversified Financials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=SCAP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Serendib Engineering Group PLC",
"cse_symbol": "IDL.N0000",
"board": "Dirisavi Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=IDL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Union Chemicals Lanka PLC",
"cse_symbol": "UCAR.N0000",
"board": "Main Board",
"sector": "Materials",
"industry_group": "Materials",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=UCAR.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Cargills Bank PLC",
"cse_symbol": "CBNK.N0000",
"board": "Main Board",
"sector": "Banks",
"industry_group": "Banks",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CBNK.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Cable Solutions PLC",
"cse_symbol": "CSOL.N0000",
"board": "Dirisavi Board",
"sector": "Capital Goods",
"industry_group": "Capital Goods",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=CSOL.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Maharaja Foods PLC",
"cse_symbol": "MFP.N0000",
"board": "Empower Board",
"sector": "Food Beverage & Tobacco",
"industry_group": "Food Beverage & Tobacco",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MFP.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
},
{
"company_name": "Morison PLC",
"cse_symbol": "MORI.N0000",
"board": "Main Board",
"sector": "Pharmaceuticals, Biotechnology & Life Sciences",
"industry_group": "Pharmaceuticals, Biotechnology & Life Sciences",
"company_id_if_available": None,
"company_profile_url": "https://www.cse.lk/pages/company-profile/company-profile.component.html?symbol=MORI.N0000",
"status": "active",
"source_url": "https://www.cse.lk",
"source_checked_date": "2026-05-01"
}
]

In [ ]:
import requests
import pandas as pd
import time



# ==============================
# API CONFIG
# ==============================
API_URL = "https://www.cse.lk/api/getFinancialAnnouncement"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Content-Type": "application/x-www-form-urlencoded"
}

# ==============================
# TEST COMPANY ID
# ==============================
def test_company_id(company_id, expected_symbol):
    payload = {
        "companyIds": str(company_id),
        "fromDate": "2021-01-01",
        "toDate": "2026-05-01"
    }

    try:
        r = requests.post(API_URL, headers=headers, data=payload, timeout=20)

        if r.status_code != 200:
            return None

        records = r.json().get("reqFinancialAnnouncemnets", [])

        if not records:
            return None

        df = pd.DataFrame(records)

        if df.empty:
            return None

        found_symbol = df["symbol"].iloc[0]

        # Remove .N0000 for comparison
        if found_symbol == expected_symbol.replace(".N0000", ""):
            return {
                "company_id": company_id,
                "symbol": found_symbol,
                "company_name_api": df["name"].iloc[0],
                "report_count": len(df)
            }

    except:
        return None

    return None

# ==============================
# FIND COMPANY ID
# ==============================
def find_company_id(symbol, start_id=1, end_id=700):
    print(f"\n🔍 Finding ID for {symbol}")

    for cid in range(start_id, end_id + 1):
        result = test_company_id(cid, symbol)

        if result:
            print(f"✅ Found: {symbol} → ID {cid}")
            return result

    print(f"❌ Not found: {symbol}")
    return None

# ==============================
# MAIN LOOP
# ==============================
results = []

for i, company in enumerate(COMPANY_JSON, start=1):
    symbol = company.get("cse_symbol")

    print(f"\n[{i}/{len(COMPANY_JSON)}] Processing {symbol}")

    result = find_company_id(symbol)

    if result:
        company["company_id"] = result["company_id"]
        company["verified_name"] = result["company_name_api"]
        company["report_count"] = result["report_count"]
    else:
        company["company_id"] = None
        company["verified_name"] = None
        company["report_count"] = 0

    results.append(company)

    # avoid hitting server too fast
    time.sleep(0.5)

# ==============================
# SAVE OUTPUT
# ==============================
df = pd.DataFrame(results)

output_file = "cse_company_master_with_ids.csv"
df.to_csv(output_file, index=False)

print("\n✅ DONE")
print("Saved:", output_file)
print("Total companies:", len(df))
print("Found IDs:", df["company_id"].notna().sum())

[1/267] Processing JKH.N0000

🔍 Finding ID for JKH.N0000
✅ Found: JKH.N0000 → ID 508

[2/267] Processing COMB.N0000

🔍 Finding ID for COMB.N0000
✅ Found: COMB.N0000 → ID 369

[3/267] Processing HNB.N0000

🔍 Finding ID for HNB.N0000
✅ Found: HNB.N0000 → ID 373

[4/267] Processing SAMP.N0000

🔍 Finding ID for SAMP.N0000
✅ Found: SAMP.N0000 → ID 431

[5/267] Processing NDB.N0000

🔍 Finding ID for NDB.N0000
✅ Found: NDB.N0000 → ID 386

[6/267] Processing DFCC.N0000

🔍 Finding ID for DFCC.N0000
✅ Found: DFCC.N0000 → ID 371

[7/267] Processing NTB.N0000

🔍 Finding ID for NTB.N0000
✅ Found: NTB.N0000 → ID 387

[8/267] Processing SEYB.N0000

🔍 Finding ID for SEYB.N0000
✅ Found: SEYB.N0000 → ID 443

[9/267] Processing PABC.N0000

🔍 Finding ID for PABC.N0000
✅ Found: PABC.N0000 → ID 388

[10/267] Processing ABL.N0000

🔍 Finding ID for ABL.N0000
❌ Not found: ABL.N0000

[11/267] Processing DIAL.N0000

🔍 Finding ID for DIAL.N0000
✅ Found: DIAL.N0000 → ID 389

[12/267] Processing SLTL.N0000

🔍 Finding ID for SLTL.N0000
✅ Found: SLTL.N0000 → ID 390

[13/267] Processing LIOC.N0000

🔍 Finding ID for LIOC.N0000
❌ Not found: LIOC.N0000

[14/267] Processing MELS.N0000

🔍 Finding ID for MELS.N0000
❌ Not found: MELS.N0000

[15/267] Processing DIST.N0000

🔍 Finding ID for DIST.N0000
✅ Found: DIST.N0000 → ID 463

[16/267] Processing CARS.N0000

🔍 Finding ID for CARS.N0000
✅ Found: CARS.N0000 → ID 502

[17/267] Processing BUKI.N0000

🔍 Finding ID for BUKI.N0000
✅ Found: BUKI.N0000 → ID 456

[18/267] Processing CTC.N0000

🔍 Finding ID for CTC.N0000
✅ Found: CTC.N0000 → ID 460

[19/267] Processing LMF.N0000

🔍 Finding ID for LMF.N0000
✅ Found: LMF.N0000 → ID 486

[20/267] Processing CCS.N0000

🔍 Finding ID for CCS.N0000
✅ Found: CCS.N0000 → ID 462

[21/267] Processing KFP.N0000

🔍 Finding ID for KFP.N0000
✅ Found: KFP.N0000 → ID 483

[22/267] Processing WATA.N0000

🔍 Finding ID for WATA.N0000
❌ Not found: WATA.N0000

[23/267] Processing HAYL.N0000

🔍 Finding ID for HAYL.N0000
✅ Found: HAYL.N0000 → ID 505

[24/267] Processing SPEN.N0000

🔍 Finding ID for SPEN.N0000
✅ Found: SPEN.N0000 → ID 501

[25/267] Processing RICH.N0000

🔍 Finding ID for RICH.N0000
✅ Found: RICH.N0000 → ID 509

[26/267] Processing SHL.N0000

🔍 Finding ID for SHL.N0000
❌ Not found: SHL.N0000

[27/267] Processing VONE.N0000

🔍 Finding ID for VONE.N0000
❌ Not found: VONE.N0000

[28/267] Processing RCL.N0000

🔍 Finding ID for RCL.N0000
✅ Found: RCL.N0000 → ID 683

[29/267] Processing AEL.N0000

🔍 Finding ID for AEL.N0000
❌ Not found: AEL.N0000

[30/267] Processing HHL.N0000

🔍 Finding ID for HHL.N0000
✅ Found: HHL.N0000 → ID 506

[31/267] Processing LOLC.N0000

🔍 Finding ID for LOLC.N0000
✅ Found: LOLC.N0000 → ID 378

[32/267] Processing LFIN.N0000

🔍 Finding ID for LFIN.N0000
✅ Found: LFIN.N0000 → ID 379

[33/267] Processing CFIN.N0000

🔍 Finding ID for CFIN.N0000
✅ Found: CFIN.N0000 → ID 366

[34/267] Processing COCR.N0000

🔍 Finding ID for COCR.N0000
❌ Not found: COCR.N0000

[35/267] Processing PLC.N0000

🔍 Finding ID for PLC.N0000
❌ Not found: PLC.N0000

[36/267] Processing CINS.N0000

🔍 Finding ID for CINS.N0000
✅ Found: CINS.N0000 → ID 367

[37/267] Processing SINS.N0000

🔍 Finding ID for SINS.N0000
❌ Not found: SINS.N0000

[38/267] Processing LLUB.N0000

🔍 Finding ID for LLUB.N0000
✅ Found: LLUB.N0000 → ID 668

[39/267] Processing TKYO.N0000

🔍 Finding ID for TKYO.N0000
✅ Found: TKYO.N0000 → ID 688

[40/267] Processing ASIR.N0000

🔍 Finding ID for ASIR.N0000
✅ Found: ASIR.N0000 → ID 512

[41/267] Processing NHL.N0000

🔍 Finding ID for NHL.N0000
❌ Not found: NHL.N0000

[42/267] Processing TYRE.N0000

🔍 Finding ID for TYRE.N0000
✅ Found: TYRE.N0000 → ID 673

[43/267] Processing TJL.N0000

🔍 Finding ID for TJL.N0000
❌ Not found: TJL.N0000

[44/267] Processing WIND.N0000

🔍 Finding ID for WIND.N0000
❌ Not found: WIND.N0000

[45/267] Processing VLL.N0000

🔍 Finding ID for VLL.N0000
✅ Found: VLL.N0000 → ID 455

[46/267] Processing AHUN.N0000

🔍 Finding ID for AHUN.N0000
✅ Found: AHUN.N0000 → ID 521

[47/267] Processing AHPL.N0000

🔍 Finding ID for AHPL.N0000
✅ Found: AHPL.N0000 → ID 690

[48/267] Processing TAJ.N0000

🔍 Finding ID for TAJ.N0000
✅ Found: TAJ.N0000 → ID 604

[49/267] Processing GHLL.N0000

🔍 Finding ID for GHLL.N0000
✅ Found: GHLL.N0000 → ID 541

[50/267] Processing KHL.N0000

🔍 Finding ID for KHL.N0000
✅ Found: KHL.N0000 → ID 561

[51/267] Processing BIL.N0000

🔍 Finding ID for BIL.N0000
❌ Not found: BIL.N0000

[52/267] Processing BRWN.N0000

🔍 Finding ID for BRWN.N0000
❌ Not found: BRWN.N0000

[53/267] Processing TILE.N0000

🔍 Finding ID for TILE.N0000
✅ Found: TILE.N0000 → ID 677

[54/267] Processing LWL.N0000

🔍 Finding ID for LWL.N0000
✅ Found: LWL.N0000 → ID 678

[55/267] Processing DIPD.N0000

🔍 Finding ID for DIPD.N0000
✅ Found: DIPD.N0000 → ID 670

[56/267] Processing HAYC.N0000

🔍 Finding ID for HAYC.N0000
✅ Found: HAYC.N0000 → ID 494

[57/267] Processing KVAL.N0000

🔍 Finding ID for KVAL.N0000
❌ Not found: KVAL.N0000

[58/267] Processing TTE.N0000

🔍 Finding ID for TTE.N0000